### ISSUE TITLE
File Missing: my_utility.py

### ISSUE THREAD

**Issue by dongmingli-Ben** [Privilger/RoboMaster-Simulator#10]
**Describe the bug**
In line 12 of the file ```src/competition_rl/scripts/robo_instance.py```, ```my_utility``` is imported but there is no python packages named *my_utility* nor python file named ```my_utility.py```. I suspect that a file named ```my_utility.py``` is missing.

**To Reproduce**
Run the following command
```bash
roslaunch competition_rl start_training.launch
```

**Expected behavior**
Run normally without error

**Desktop (please complete the following information):**
 - Ubuntu Version: Ubuntu 18.04
 - ROS Version: melodic

**Comment by yizhengzhang1** [comment]
Hi, **my_utility.py** has been uploaded. It is used to set the action of the robot. You can define your own robot actions according to your case. Ignore my actions setting is totally fine.

**Comment by dongmingli-Ben** [comment]
Thanks. The issue resolved with the uploaded file.

However, when running ```roslaunch competition_rl start_training.launch```, it keeps telling me ```[ERROR] [1637326293.086782]: Current /jackal0/joint_states not ready yet, retrying for getting joint_states```. Is this a normal thing or something is actually broken?

Thanks!
