### ISSUE TITLE
编译报错询问

### ISSUE THREAD

**Issue by sunshihao1010** [Privilger/RoboMaster-Simulator#2]
In file included from /home/sunshihao/RoboMaster-Simulator/src/pointgrey_camera_driver/pointgrey_camera_driver/src/PointGreyCamera.cpp:32:0:
/home/sunshihao/RoboMaster-Simulator/src/pointgrey_camera_driver/pointgrey_camera_driver/include/pointgrey_camera_driver/PointGreyCamera.h:46:10: fatal error: flycapture/FlyCapture2.h: 没有那个文件或目录
 #include "flycapture/FlyCapture2.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
你好，我在编译你的RoboMaster-Simulator包时显示你缺少这个头文件，请问是你忘记上传了吗？还是我这边出什么问题了，希望你能抽出时间尽快回复一下，十分感谢。

**Comment by yizhengzhang1** [comment]
你好，

应该是driver没装，这个driver是目录下的flycapture2-2.11.3.121-amd64-pkg.tgz文件，请根据README安装。
