### ISSUE TITLE
问题询问

### ISSUE THREAD

**Issue by sunshihao1010** [Privilger/RoboMaster-Simulator#3]
你好，非常感谢你之前的快速回复，我按照你的说明进行了安装，不过后续还是遇到一些问题，我之前向你发过一封电子邮件，想再请教一些问题，你应该是没有看到，如果可以的话我希望能加一下你的联系方式，希望能和你进一步讨论一下gazebo仿真的相关事情，我的qq号是1256183649，非常感谢！

**Comment by Privilger** [comment]
没有收到邮件，不知道是不是你发错地址了。

有什么问题还是直接这里提issue比较方便吧，你的问题也可能是别人的问题，这样别人也可以看到。

最后，给个star支持一下吧⭐️
