### ISSUE TITLE
报错询问

### ISSUE THREAD

**Issue by sunshihao1010** [Privilger/RoboMaster-Simulator#4]
好的，是这样，我按照readme的步骤安装，执行sudo sh install_flycapture.sh，安装过程中有一步要求我输入添加的用户名，我输入的是我的Ubuntu18.04的用户名sunshihao，安装结束后运行catkin_make,结果报错如下：

make[2]: *** 没有规则可制作目标“/home/sunshihao/RoboMaster-Simulator/devel/lib/libflycapture.so.2”，由“/home/sunshihao/RoboMaster-Simulator/devel/lib/libPointGreyCamera.so” 需求。 停止。
CMakeFiles/Makefile2:16278: recipe for target 'pointgrey_camera_driver/pointgrey_camera_driver/CMakeFiles/PointGreyCamera.dir/all' failed
make[1]: *** [pointgrey_camera_driver/pointgrey_camera_driver/CMakeFiles/PointGreyCamera.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....

Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yizhengzhang1** [comment]
README 里写的是`echo "y\n" | sudo ./install_flycapture_only_simulation.sh `
