### ISSUE TITLE
继续询问

### ISSUE THREAD

**Issue by sunshihao1010** [Privilger/RoboMaster-Simulator#8]
我直接运行rosrun roborts_decision behavior_test_node
显示如下：
[ INFO] [1619767388.713756601]: !!!!!!!!!!!decision jackal_ns:
我输入jackal0、jackal_0都不对

**Comment by yizhengzhang1** [comment]
你得自己改代码实现新功能。还有你到底会不会用issue，怎么老是一句话开一个issue。
